name: cblite_sync_flutter_test
description: Couchbase Lite Flutter Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  archive: ^3.3.2
  cbl: ^3.4.2+0
  cbl_flutter: ^3.3.1
  cbl_flutter_ee: ^3.3.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
